language: java
jdk:
  - oraclejdk8

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cb192d768f68c8acc006
    on_success: change  
    on_failure: always  
    on_start: false     
